"""full schema with all source fields

Revision ID: b246f4a18315
Revises:
Create Date: 2026-04-28 01:27:50.168427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b246f4a18315"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accidents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "external_id",
            sa.BigInteger(),
            nullable=False,
            comment="EM_NUMBER из источника — уникальный ID ДТП",
        ),
        sa.Column(
            "gibdd_number",
            sa.String(length=50),
            nullable=True,
            comment="EMTP_NUMBER — номер ДТП в базе ГИБДД",
        ),
        sa.Column(
            "datetime",
            sa.DateTime(),
            nullable=False,
            comment="DATE_TIME — дата и время ДТП",
        ),
        sa.Column(
            "parent_region",
            sa.String(length=100),
            nullable=True,
            comment="Регион верхнего уровня (для нашего датасета — 'Приморский край')",
        ),
        sa.Column(
            "place",
            sa.Text(),
            nullable=True,
            comment="PLACE — городской округ или район (Владивостокский ГО, Уссурийский ГО, ...)",
        ),
        sa.Column(
            "np",
            sa.Text(),
            nullable=True,
            comment="NP — населённый пункт (г Владивосток, г Уссурийск, ...)",
        ),
        sa.Column("street", sa.Text(), nullable=True, comment="STREET — улица"),
        sa.Column("house", sa.String(length=100), nullable=True, comment="HOUSE — дом"),
        sa.Column(
            "roads",
            sa.Text(),
            nullable=True,
            comment="ROADS — название трассы (для трассовых ДТП)",
        ),
        sa.Column(
            "road_km",
            sa.Float(),
            nullable=True,
            comment="ROAD_KM_M — километр.метр трассы",
        ),
        sa.Column(
            "street_sign",
            sa.Text(),
            nullable=True,
            comment="STREET_SIGN — категория улицы (Магистральные/Местного значения)",
        ),
        sa.Column(
            "road_sign",
            sa.Text(),
            nullable=True,
            comment="ROAD_SIGN — категория дороги",
        ),
        sa.Column(
            "road_type", sa.Text(), nullable=True, comment="ROAD_TYPE — тип дороги"
        ),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
            comment="Точка на карте",
        ),
        sa.Column(
            "em_type",
            sa.Text(),
            nullable=True,
            comment="EM_TYPE — тип ДТП (Столкновение, Опрокидывание, Наезд на пешехода...)",
        ),
        sa.Column(
            "schema_id",
            sa.Integer(),
            nullable=True,
            comment="SCHEMA_ID — код схемы ДТП",
        ),
        sa.Column(
            "light_type",
            sa.Text(),
            nullable=True,
            comment="LIGHT_TYPE — освещение/время суток",
        ),
        sa.Column(
            "clouds",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="CLOUDS — погода (массив)",
        ),
        sa.Column(
            "traffic_area_state",
            sa.Text(),
            nullable=True,
            comment="TRAFFIC_AREA_STATE — состояние дорожного покрытия",
        ),
        sa.Column(
            "defects",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="DEFECTS — дефекты дорожного покрытия (массив)",
        ),
        sa.Column(
            "motion_influences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="MOTION_INFLUENCES — факторы, влияющие на движение",
        ),
        sa.Column(
            "mt_rate", sa.Text(), nullable=True, comment="MT_RATE — режим движения"
        ),
        sa.Column(
            "rd_constr_heres",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="RD_CONSTR_HERES — объекты УДС на месте ДТП",
        ),
        sa.Column(
            "rd_constr_theres",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="RD_CONSTR_THERES — объекты УДС вблизи места ДТП",
        ),
        sa.Column(
            "veh_amount",
            sa.Integer(),
            nullable=False,
            comment="VEH_AMOUNT — количество ТС в ДТП",
        ),
        sa.Column(
            "pers_amount",
            sa.Integer(),
            nullable=False,
            comment="PERS_AMOUNT — количество участников",
        ),
        sa.Column(
            "lost_amount",
            sa.Integer(),
            nullable=False,
            comment="LOST_AMOUNT — количество погибших",
        ),
        sa.Column(
            "suffer_amount",
            sa.Integer(),
            nullable=False,
            comment="SUFFER_AMOUNT — количество раненых",
        ),
        sa.Column(
            "children_attr",
            sa.Integer(),
            nullable=True,
            comment="CHILDREN_ATTR — количество детей среди участников",
        ),
        sa.Column(
            "additional_attr",
            sa.Integer(),
            nullable=True,
            comment="ADDITIONAL_ATTR — дополнительный атрибут (значение из источника)",
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=True,
            comment="Вычисляемая тяжесть: dead/injured/minor",
        ),
        sa.Column(
            "raw_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Полная запись из источника (для будущих расширений)",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accidents_datetime"), "accidents", ["datetime"], unique=False
    )
    op.create_index(
        "ix_accidents_datetime_severity",
        "accidents",
        ["datetime", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accidents_em_type"), "accidents", ["em_type"], unique=False
    )
    op.create_index(
        "ix_accidents_em_type_severity",
        "accidents",
        ["em_type", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accidents_external_id"), "accidents", ["external_id"], unique=True
    )
    op.create_index(
        op.f("ix_accidents_lost_amount"), "accidents", ["lost_amount"], unique=False
    )
    op.create_index(op.f("ix_accidents_place"), "accidents", ["place"], unique=False)
    op.create_index(
        op.f("ix_accidents_severity"), "accidents", ["severity"], unique=False
    )
    op.create_table(
        "data_updates_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Источник: dtp-stat-accumulated / mvd-25",
        ),
        sa.Column("records_added", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="success / error / running",
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accident_pedestrians",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("accident_id", sa.BigInteger(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=True),
        sa.Column("part_type", sa.Text(), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("driver_service_length", sa.Integer(), nullable=True),
        sa.Column("hv_type", sa.Text(), nullable=True),
        sa.Column("injured_card", sa.Text(), nullable=True),
        sa.Column("safety_belt", sa.String(length=20), nullable=True),
        sa.Column("child_safety_type", sa.Text(), nullable=True),
        sa.Column(
            "med_result_permille", sa.Numeric(precision=5, scale=3), nullable=True
        ),
        sa.Column("escape", sa.Text(), nullable=True),
        sa.Column(
            "main_pdd_violation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "attendant_pdd_violation",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["accident_id"], ["accidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accident_pedestrians_accident_id"),
        "accident_pedestrians",
        ["accident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accident_pedestrians_part_type"),
        "accident_pedestrians",
        ["part_type"],
        unique=False,
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("accident_id", sa.BigInteger(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=True, comment="N — номер ТС в этом ДТП"),
        sa.Column("mark", sa.String(length=100), nullable=True, comment="MARK — марка"),
        sa.Column(
            "model", sa.String(length=200), nullable=True, comment="MODEL — модель"
        ),
        sa.Column(
            "vehicle_year",
            sa.Integer(),
            nullable=True,
            comment="VEHICLE_YEAR — год выпуска",
        ),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column(
            "prod_type", sa.Text(), nullable=True, comment="PROD_TYPE — категория ТС"
        ),
        sa.Column(
            "okfs", sa.Text(), nullable=True, comment="OKFS — форма собственности"
        ),
        sa.Column(
            "okopf",
            sa.Text(),
            nullable=True,
            comment="OKOPF — организационно-правовая форма владельца",
        ),
        sa.Column(
            "rudder_type",
            sa.Text(),
            nullable=True,
            comment="RUDDER_TYPE — тип привода (передний/задний/полный)",
        ),
        sa.Column(
            "tech_failure_type",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="TECH_FAILURE_TYPE — технические неисправности",
        ),
        sa.Column(
            "damage_disposition",
            sa.Text(),
            nullable=True,
            comment="DAMAGE_DISPOSITION — расположение повреждений",
        ),
        sa.Column(
            "escape",
            sa.Text(),
            nullable=True,
            comment="ESCAPE — скрылся ли с места ДТП",
        ),
        sa.Column(
            "is_right_hand_drive",
            sa.Boolean(),
            nullable=True,
            comment="Правый руль (вычисляется по справочнику марок)",
        ),
        sa.Column(
            "steering_confidence",
            sa.String(length=10),
            nullable=True,
            comment="Уверенность определения: high/medium/low",
        ),
        sa.ForeignKeyConstraint(["accident_id"], ["accidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicles_accident_id"), "vehicles", ["accident_id"], unique=False
    )
    op.create_index(op.f("ix_vehicles_mark"), "vehicles", ["mark"], unique=False)
    op.create_table(
        "participants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vehicle_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "n", sa.Integer(), nullable=True, comment="N — номер участника внутри ТС"
        ),
        sa.Column(
            "part_type",
            sa.Text(),
            nullable=True,
            comment="PART_TYPE — роль (Водитель/Пассажир/...)",
        ),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column(
            "driver_service_length",
            sa.Integer(),
            nullable=True,
            comment="DRIVER_SERVICE_LENGTH — стаж вождения (только водители)",
        ),
        sa.Column(
            "hv_type",
            sa.Text(),
            nullable=True,
            comment="HV_TYPE — состояние здоровья после ДТП",
        ),
        sa.Column(
            "injured_card",
            sa.Text(),
            nullable=True,
            comment="INJURED_CARD — медицинская карточка пострадавшего",
        ),
        sa.Column(
            "safety_belt",
            sa.String(length=20),
            nullable=True,
            comment="SAFETY_BELT — был ли пристёгнут (Да/Нет)",
        ),
        sa.Column(
            "child_safety_type",
            sa.Text(),
            nullable=True,
            comment="CHILD_SAFETY_TYPE — тип детского удерживающего устройства",
        ),
        sa.Column(
            "med_result_permille",
            sa.Numeric(precision=5, scale=3),
            nullable=True,
            comment="MED_RESULT_PERMILLE — промилле алкоголя (только водители)",
        ),
        sa.Column(
            "escape", sa.Text(), nullable=True, comment="ESCAPE — скрылся ли с места"
        ),
        sa.Column(
            "main_pdd_violation",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="MAIN_PDD_DERANGEMENT — основное нарушение ПДД",
        ),
        sa.Column(
            "attendant_pdd_violation",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="ATTENDANT_PDD_DERANGEMENT — сопутствующее нарушение",
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participants_med_result_permille"),
        "participants",
        ["med_result_permille"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participants_part_type"), "participants", ["part_type"], unique=False
    )
    op.create_index(
        op.f("ix_participants_vehicle_id"), "participants", ["vehicle_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participants_vehicle_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_part_type"), table_name="participants")
    op.drop_index(
        op.f("ix_participants_med_result_permille"), table_name="participants"
    )
    op.drop_table("participants")
    op.drop_index(op.f("ix_vehicles_mark"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_accident_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(
        op.f("ix_accident_pedestrians_part_type"), table_name="accident_pedestrians"
    )
    op.drop_index(
        op.f("ix_accident_pedestrians_accident_id"), table_name="accident_pedestrians"
    )
    op.drop_table("accident_pedestrians")
    op.drop_table("data_updates_log")
    op.drop_index(op.f("ix_accidents_severity"), table_name="accidents")
    op.drop_index(op.f("ix_accidents_place"), table_name="accidents")
    op.drop_index(op.f("ix_accidents_lost_amount"), table_name="accidents")
    op.drop_index(op.f("ix_accidents_external_id"), table_name="accidents")
    op.drop_index("ix_accidents_em_type_severity", table_name="accidents")
    op.drop_index(op.f("ix_accidents_em_type"), table_name="accidents")
    op.drop_index("ix_accidents_datetime_severity", table_name="accidents")
    op.drop_index(op.f("ix_accidents_datetime"), table_name="accidents")
    op.drop_table("accidents")
    # ### end Alembic commands ###
