"""expand steering_confidence varchar to 20

Revision ID: d90353164694
Revises: b246f4a18315
Create Date: 2026-04-28 02:50:44.167211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90353164694'
down_revision: Union[str, None] = 'b246f4a18315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'steering_confidence',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               comment='Уверенность определения: high/medium/unknown/not_applicable',
               existing_comment='Уверенность определения: high/medium/low',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'steering_confidence',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               comment='Уверенность определения: high/medium/low',
               existing_comment='Уверенность определения: high/medium/unknown/not_applicable',
               existing_nullable=True)
    # ### end Alembic commands ###
