"""add region_boundaries table

Revision ID: e99ba6807a09
Revises: d90353164694
Create Date: 2026-04-28 21:29:44.000902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99ba6807a09'
down_revision: Union[str, None] = 'd90353164694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_boundaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False, comment='Уникальный код (primorye_krai_land и т.п.) — для идемпотентного UPSERT'),
    sa.Column('display_name', sa.Text(), nullable=True, comment='Человекочитаемое название (Приморский край, суша)'),
    sa.Column('source', sa.Text(), nullable=True, comment='Источник полигона с датой выгрузки — для аудита'),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='MultiPolygon WGS84 — материк + острова'),
    sa.Column('area_km2', sa.Numeric(precision=12, scale=2), nullable=True, comment='Площадь км² (вычислена в UTM zone 52N для минимума искажений)'),
    sa.Column('raw_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='osm_relation_id, дата OSM-выгрузки, метод обработки и т.п.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GIST-индекс на geom автоматически создаётся geoalchemy2 при create_table
    # (через event handler), поэтому явный op.create_index здесь не нужен —
    # иначе на втором CREATE INDEX будет ошибка "relation already exists".
    op.create_index(op.f('ix_region_boundaries_region_name'), 'region_boundaries', ['region_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_boundaries_region_name'), table_name='region_boundaries')
    op.drop_index('idx_region_boundaries_geom', table_name='region_boundaries', postgresql_using='gist')
    op.drop_table('region_boundaries')
    # ### end Alembic commands ###
