"""add accidents.is_in_region column

Revision ID: ec580a6e805d
Revises: e99ba6807a09
Create Date: 2026-04-28 21:55:17.891455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec580a6e805d'
down_revision: Union[str, None] = 'e99ba6807a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accidents', sa.Column('is_in_region', sa.Boolean(), nullable=True, comment='True если point внутри region_boundaries (суша Приморья); False если в воде/вне региона (дефекты #6 и #7); NULL если не вычислено или point IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accidents', 'is_in_region')
    # ### end Alembic commands ###
